#!/bin/bash

echo "------------------deploy to green slice----------------"
docker pull localhost:5000/hw4:latest  
docker stop app-green  
docker rm app-green
docker rmi localhost:5000/hw4:current  
docker tag localhost:5000/hw4:latest localhost:5000/hw4:current
docker run -p 3002:8080 -d --name app-green localhost:5000/hw4:latest  
