#!/bin/bash

echo "------------------deploy to blue slice----------------"
docker pull localhost:5000/hw4:latest  
docker stop app-blue  
docker rm app-blue
docker rmi localhost:5000/hw4:current  
docker tag localhost:5000/hw4:latest localhost:5000/hw4:current
docker run -p 3001:8080 -d --name app-blue localhost:5000/hw4:latest  
